repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace      # Removes unnecessary trailing spaces
      - id: end-of-file-fixer        # Ensures files end with a newline
      - id: check-yaml               # Validates YAML syntax
      - id: check-added-large-files  # Prevents accidentally committing huge files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.20
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    # Run pytest tests
    hooks:
      - id: pytest
        name: run pytest
        # entry: bash -c "cd backend && python -m pytest"
        entry: powershell -Command "cd backend; python -m pytest"
        language: system
        pass_filenames: false # Tells pre-commit to run all tests
        files: ^backend/ # Only run if files in backend change
        stages: [pre-commit]
