# ==========================================
# AdventureWorks Data Warehouse CSV Headers
# ==========================================

fact_internet_sales = [
    "ProductKey",
    "OrderDateKey",
    "DueDateKey",
    "ShipDateKey",
    "CustomerKey",
    "PromotionKey",
    "CurrencyKey",
    "SalesTerritoryKey",
    "SalesOrderNumber",
    "SalesOrderLineNumber",
    "RevisionNumber",
    "OrderQuantity",
    "UnitPrice",
    "ExtendedAmount",
    "UnitPriceDiscountPct",
    "DiscountAmount",
    "ProductStandardCost",
    "TotalProductCost",
    "SalesAmount",
    "TaxAmt",
    "Freight",
    "CarrierTrackingNumber",
    "CustomerPONumber",
    "OrderDate",
    "DueDate",
    "ShipDate",
]

dim_customer = [
    "CustomerKey",
    "GeographyKey",
    "CustomerAlternateKey",
    "Title",
    "FirstName",
    "MiddleName",
    "LastName",
    "NameStyle",
    "BirthDate",
    "MaritalStatus",
    "Suffix",
    "Gender",
    "EmailAddress",
    "YearlyIncome",
    "TotalChildren",
    "NumberChildrenAtHome",
    "EnglishEducation",
    "SpanishEducation",
    "FrenchEducation",
    "EnglishOccupation",
    "SpanishOccupation",
    "FrenchOccupation",
    "HouseOwnerFlag",
    "NumberCarsOwned",
    "AddressLine1",
    "AddressLine2",
    "Phone",
    "DateFirstPurchase",
    "CommuteDistance",
]

dim_product = [
    "ProductKey",
    "ProductAlternateKey",
    "ProductSubcategoryKey",
    "WeightUnitMeasureCode",
    "SizeUnitMeasureCode",
    "EnglishProductName",
    "SpanishProductName",
    "FrenchProductName",
    "StandardCost",
    "FinishedGoodsFlag",
    "Color",
    "SafetyStockLevel",
    "ReorderPoint",
    "ListPrice",
    "Size",
    "SizeRange",
    "Weight",
    "DaysToManufacture",
    "ProductLine",
    "DealerPrice",
    "Class",
    "Style",
    "ModelName",
    "LargePhoto",
    "EnglishDescription",
    "FrenchDescription",
    "ChineseDescription",
    "ArabicDescription",
    "HebrewDescription",
    "ThaiDescription",
    "GermanDescription",
    "JapaneseDescription",
    "TurkishDescription",
    "StartDate",
    "EndDate",
    "Status",
]

dim_date = [
    "DateKey",
    "FullDateAlternateKey",
    "DayNumberOfWeek",
    "EnglishDayNameOfWeek",
    "SpanishDayNameOfWeek",
    "FrenchDayNameOfWeek",
    "DayNumberOfMonth",
    "DayNumberOfYear",
    "WeekNumberOfYear",
    "EnglishMonthName",
    "SpanishMonthName",
    "FrenchMonthName",
    "MonthNumberOfYear",
    "CalendarQuarter",
    "CalendarYear",
    "CalendarSemester",
    "FiscalQuarter",
    "FiscalYear",
    "FiscalSemester",
]

dim_geography = [
    "GeographyKey",
    "City",
    "StateProvinceCode",
    "StateProvinceName",
    "CountryRegionCode",
    "EnglishCountryRegionName",
    "SpanishCountryRegionName",
    "FrenchCountryRegionName",
    "PostalCode",
    "SalesTerritoryKey",
    "IpAddressLocator",
]

dim_currency = ["CurrencyKey", "CurrencyAlternateKey", "CurrencyName"]

dim_promotion = [
    "PromotionKey",
    "PromotionAlternateKey",
    "EnglishPromotionName",
    "SpanishPromotionName",
    "FrenchPromotionName",
    "DiscountPct",
    "EnglishPromotionType",
    "SpanishPromotionType",
    "FrenchPromotionType",
    "EnglishPromotionCategory",
    "SpanishPromotionCategory",
    "FrenchPromotionCategory",
    "StartDate",
    "EndDate",
    "MinQty",
    "MaxQty",
]

dim_sales_territory = [
    "SalesTerritoryKey",
    "SalesTerritoryAlternateKey",
    "SalesTerritoryRegion",
    "SalesTerritoryCountry",
    "SalesTerritoryGroup",
]

dim_product_category = [
    "ProductCategoryKey",
    "ProductCategoryAlternateKey",
    "EnglishProductCategoryName",
    "SpanishProductCategoryName",
    "FrenchProductCategoryName",
]

dim_product_subcategory = [
    "ProductSubcategoryKey",
    "ProductSubcategoryAlternateKey",
    "EnglishProductSubcategoryName",
    "SpanishProductSubcategoryName",
    "FrenchProductSubcategoryName",
    "ProductCategoryKey",
]

dim_employee = [
    "EmployeeKey",
    "ParentEmployeeKey",
    "EmployeeNationalIDAlternateKey",
    "ParentEmployeeNationalIDAlternateKey",
    "SalesTerritoryKey",
    "FirstName",
    "LastName",
    "MiddleName",
    "NameStyle",
    "Title",
    "HireDate",
    "BirthDate",
    "LoginID",
    "EmailAddress",
    "Phone",
    "MaritalStatus",
    "EmergencyContactName",
    "EmergencyContactPhone",
    "SalariedFlag",
    "Gender",
    "PayFrequency",
    "BaseRate",
    "VacationHours",
    "SickLeaveHours",
    "CurrentFlag",
    "SalesPersonFlag",
    "DepartmentName",
    "StartDate",
    "EndDate",
    "Status",
]

dim_reseller = [
    "ResellerKey",
    "GeographyKey",
    "ResellerAlternateKey",
    "Phone",
    "BusinessType",
    "ResellerName",
    "NumberEmployees",
    "OrderFrequency",
    "OrderMonth",
    "FirstOrderYear",
    "LastOrderYear",
    "ProductLine",
    "AddressLine1",
    "AddressLine2",
    "AnnualSales",
    "BankName",
    "MinPaymentType",
    "MinPaymentAmount",
    "AnnualRevenue",
    "YearOpened",
]
